[build]
  base = "app/app"                     # inner app folder
  command = "npm install && npm run build"
  publish = ".netlify"                 # relative to base, plugin will populate it

[[plugins]]
  package = "@netlify/plugin-nextjs"
