# ---------------------------
# Netlify build config for Next.js
# Works with SSR/API routes or static export
# ---------------------------

[build]
  # Path to your Next.js app folder
  base = "app"

  # Build command
  command = "npm install && npm run build"

  # Publish directory — plugin handles SSR output
  publish = "app"

  # Clear any cached previous settings to avoid UI overrides
  publishOrigin = "config"
  commandOrigin = "config"
  baseOrigin = "config"

# Enable the Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  inputs = {}
