# ---------------------------
# Netlify build config for Next.js
# Works with SSR/API routes or static export
# ---------------------------

[build]
  base = "app"                      # your Next.js folder
  command = "npm install && npm run build"
  publish = "."                     # <--- current folder (inside base)
  
[[plugins]]
  package = "@netlify/plugin-nextjs"
