[build]
  base = "app"                       # your Next.js folder
  command = "npm install && npm run build"
  publish = "app/.netlify"           # a folder different from base for Netlify output

[[plugins]]
  package = "@netlify/plugin-nextjs"
